// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010_update_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1, hashed_password = $2
WHERE id = $3
`

type UpdateUserParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
