name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: chirpy_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Create .env.test file
        run: |
          echo "DB_URL=postgres://postgres@localhost:5432/chirpy_test?sslmode=disable" > .env.test
          echo "PLATFORM=TEST" >> .env.test
          echo "SECRET=Ra0X6gVbT5yL3UR6bssmsFPXcyUqhhQ24ZXxzjkbhC0IDetGt9Ull8XE7DAZvQcwLkjQj9kNQKvGYLmkfFrXAw==" >> .env.test

      - name: Test
        run: go test -v ./...